spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8082/
          predicates : 
            - Path= /myConfig
        - id : r2
          uri : http://localhost:8083/
          predicates : 
            - Path= /myConfig
        - id : r3
          uri : http://localhost:8082/
          predicates : 
            - Path= /company/*
        - id : r4
          uri : http://localhost:8083/
          predicates : 
            - Path=/company/* 
        - id : r5
          uri : http://localhost:8083/
          predicates : 
            - Path=/companies 
        - id : r6
          uri : http://localhost:8082/
          predicates : 
            - Path=/companies 
    discovery:      enabled: false          
server:  port: 8080 